name: deploy

on:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo ${{ github.event.ref }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"

      - name: Get yarn cache
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          yarn cache dir

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: |
          yarn

      - name: generate
        run: |
          yarn run md
          yarn run generate

      - name: upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  create-release:
    runs-on: ubuntu-latest
    needs: generate
    if: github.event.ref == 'refs/heads/master'
    steps:
      - name: download dist
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: zip
        run: zip -r dist.zip ./dist

      - name: Trigger Webhook to CoreServer
        run: curl https://ku-unplugged.net/deploy.php?token=${{ secrets.CORESERVER_DEPLOY_KEY }}
